version: "3.9"

x-env: &env
  env_file:
    - .env

services:
  web:
    <<: *env
    container_name: web
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./migrations/versions:/app/migrations/versions

  db:
    <<: *env
    container_name: db
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    <<: *env
    container_name: redis
    image: redis:7.2.4-alpine
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  pg_data:
  redis_data:
