class InvalidEmailCharacters(Exception): ...


class InvalidEmailDomain(Exception): ...


class InvalidPassword(Exception): ...


class IncompletePassword(Exception): ...


class MismatchedPasswords(Exception): ...
